### ISSUE TITLE
windows下运行不了。。。node 8.9.3 win10

### ISSUE THREAD

**Issue by loveshullf** [hubcarl/easywebpack-cli#1]
![image](https://user-images.githubusercontent.com/15190244/34246217-8d201906-e668-11e7-807f-20b780bf4c13.png)

**Comment by cooleone** [comment]
阿里云里也不行了

**Comment by cooleone** [comment]
退回到1.3.0还能正常

**Comment by loveshullf** [comment]
新版本不能用 老版本没问题

**Comment by hubcarl** [comment]
好，今天看看

**Comment by hubcarl** [comment]
npm i easywebpack-cli -g  安装不了？刚虚拟机装了一下，是可以的，你这边再试试，看看是否有问题

**Comment by cooleone** [comment]
安装是能正常安装的，但是执行build命令时有问题

**Comment by hubcarl** [comment]
@cooleone  npm start 可以运行不？ 如果方便可以加QQ交流群: 433207205， 然后可以单独找我(sky)
