### ISSUE TITLE
文档全是从你们自己的角度去写的

### ISSUE THREAD

**Issue by squallyan** [hubcarl/easywebpack-cli#4]
以为很简单，对着撸根本没用，还得看那该死的源码

**Comment by Jemair** [comment]
站作者  文档已经很详细了  其他关于webpack的配置请移步webpack文档

**Comment by hubcarl** [comment]
@squallyan  欢迎提意见，你在哪些方面不清楚？ 我可以再补充。https://yuque.com/hubcarl/easywebpack

**Comment by szalansun** [comment]
文档根本没看懂
而且， 为什么 easywebpack  build 没有watch 模式？

**Comment by hubcarl** [comment]
@szalansun   build 只会构建， 纯前端应用开发用 easy start 或者 easy server 启动

**Comment by hubcarl** [comment]
@squallyan  @szalansun  文档如有兴趣，可以参与进来
